[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
fs_extra = "1.3.0"
nix = { version = "0.28.0", features = ["user", "signal"] }
once_cell = "1.19.0"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
dtor = "0"
libc-print = "0"
[target.'cfg(unix)'.dependencies]
command-fds = "0.3.0"
